---
title: Publication
---


You can retrieve all all publications on [Google Scholar](https://scholar.google.com/citations?user=djmP82AAAAAJ&hl=en&inst=12733411405069140160&authuser=1) and [Research Gate](https://www.researchgate.net/profile/Xiaoxiao-Li-13?ev=hdr_xprf).


## 2025:

29. **Li X.**, Yang W., Novak M., Zhao L., de Ruiter P.C., Yang Z., & Guill C. (2025). Body mass-biomass scaling modulates species keystone-ness to press perturbations. Ecology Letters, 28(2), e70086.

<!-- -->

28. Gaedke U., **Li X.**, Guill C., Hemerik L., & de Ruiter P.C. (2025). Seasonal shifts in trophic interaction strength drive stability of natural food webs. Ecology Letters, 28(1), e70075.

<!-- -->

27. **Li X.**, Gaedke U., Wacker A., Schulze B., Yang Z., Moorthi S., ... & Klauschies T. (2025). Coadaptation shapes ecological interactions in mixotroph-resource systems. Oikos, e11054.

<!-- -->

26. **Li X.**, Xu Z., Zhang S., Gao W., Dong Q., Guo F., ... & Yang Z. (2025). Eutrophication-driven changes in plankton trophic interactions: insights from trade-offs in functional traits. Environmental Science & Technology, 59, 744-755.

<!-- -->

25. Yao, W., Yang, W., Fu, X., **Li, X.**, & Sun, T. (2025). Quantifying energy fluxes and trophic dynamics to assess artificial reef restoration success: Evidence from Bohai Bay, China. Estuarine, Coastal and Shelf Science, 109467.

<!-- -->

24. Yang, W., Zhang, Z., **Li, X.**, Zhao, J., & Sun, T. (2025). Comparing food web structure and trophic diversity between natural and artificial habitats: a case study in the Bohai Sea, China. Marine Biology, 172(6), 85.

<!-- -->

23. Jiao, L., Zhang, P., **Li, X.**, Yang, W., & Sun, T. (2025). Escalating climatic and anthropogenic disturbances drive a fragmented and squeezed vegetation pattern: a case study in the Yellow River Delta from 1990 to 2020. Environmental and Sustainability Indicators, 100734.

<!-- -->

22. Liu, X., Yang, W., **Li, X.**, Ding, J., Sun, T., & Liu, H. (2025). Water regulation weakens the relationship between biodiversity and ecosystem multifunctionality: Insights from a highly managed Chinese lake. Journal of Environmental Management, 373, 124003.

<!-- -->

21. Dong, Q., Xu, Z., Chen, Y., **Li, X.**, Fan, W., Xue, J., ... & Yang, Z. (2025). Heterogeneous saltwater intrusion patterns and drivers among multiple outlets in a complex estuary. Journal of Environmental Management, 393, 126896.

<!-- -->

20. Wu, Y., Yang, W., Liu, J., **Li, X.**, & Cui, B. (2025). Eutrophication drives resource use efficiency variations in freshwater plankton communities across river–lake continuum in China’s Poyang Lake Basin. Hydrobiologia, 1-17.

## 2024:

19. **Li X.**, Yang W., Jiao L., Sun T., & Yang Z. (2024). Sediment water content drives movement of intertidal crab Helice tientsinensis more strongly than salinity variations. Marine Environmental Research, 201, 106711.

<!-- -->

18. Liu, X., Yang, W., Fu, X., & **Li, X.** (2024). Determination of the ecological water levels in shallow lakes based on regime shifts: A case study of China's Baiyangdian Lake. Ecohydrology & Hydrobiology, 24(4), 931-943.

<!-- -->

17. Xu, C., Xu, Z., **Li, X.**, & Yang, Z. (2024). Integrated simulation-surrogate-optimization modeling framework for multiple tradeoffs among socioeconomic and ecological targets in reservoir operations. Journal of Environmental Management, 368, 122092.

<!-- -->

16. Liu, X., Sun, T., Yang, W., **Li, X.**, Ding, J., & Fu, X. (2024). Meta-analysis to identify inhibition mechanisms for the effects of submerged plants on algae. Journal of Environmental Management, 355, 120480.

## 2023:

15. **Li X.**, Yang W., Ma X., Zhu Z., Sun T., Cui B., & Yang Z. (2023). Invasive Spartina alterniflora habitat forms high energy fluxes but low food web stability compared to adjacent native vegetated habitats. Journal of Environmental Management, 334, 117487.

<!-- -->

14. **Li X.**, Klauschies T., Yang W., Yang Z., & Gaedke U. (2023). Trait adaptation enhances species coexistence and reduces bistability in an intraguild predation module. Ecology and Evolution, 13, e9749.

<!-- -->

13. Feng, J., Li, S., **Li, X.**, Jiang, Y., Wang, R., Meng, X., ... & Stenseth, N. C. (2023). Coupling strength between omnivory loops and their one-species-delete subloops drives real food web stability. Theoretical Ecology, 16(4), 327-338. 2022:

<!-- -->

12. **Li X.**, Yang W., Sun T., & Yang Z. (2022). Trophic diversity and food web structure of vegetated habitats along a coastal topographic gradient. Frontiers in Marine Science, 9, 920745.

<!-- -->

11. Yang, W., Fu, X., **Li, X.**, & Yang, Y. (2022). Temporal changes of the food web structure and function driven by changes in hydrological regimes and water quality in a large shallow lake. Frontiers in Environmental Science, 10, 987600.

<!-- -->

10. Fu, X., Yang, W., Zheng, L., Liu, D., & **Li, X.** (2022). Spatial patterns of macrobenthos taxonomic and functional diversity throughout the ecotones from river to lake: A case study in Northern China. Frontiers in Ecology and Evolution, 10, 922539.

## 2021:

9.  **Li X.**, Yang W., Gaedke U., & de Ruiter P.C. (2021). Energetic constraints imposed on trophic interaction strengths enhance resilience in empirical and model food webs. Journal of Animal Ecology, 90(9), 2065-2076.

<!-- -->

8.  **Li X.**, Yang W., Sun T., & Gaedke U. (2021). Quantitative food web structure and ecosystem functions in a warm-temperate seagrass bed. Marine Biology, 168(5), 74. 2020:

<!-- -->

7.  **Li X.**, Yang W., Li S., Sun T., Bai J., Pei J., ... & Cui B. (2020). Asymmetric responses of spatial variation of different communities to a salinity gradient in coastal wetlands. Marine Environmental Research, 158, 105008.

## 2019:

6.  **Li X.**, Yang W., Sun T., & Su L. (2019). Framework of multidimensional macrobenthos biodiversity to evaluate ecological restoration in wetlands. Environmental Research Letters, 14(5), 054003.

## 2018:

5.  Yang W., **Li X.**, Jin Y., & Sun T. (2018). The impact of multiple seashore reclamation activities on vegetation cover in the Yellow River Delta, China: implications based on structural equation modeling. Journal of Coastal Conservation, 22, 283-292.

<!-- -->

4.  Pei, J., Yang, W., Cai, Y., Yi, Y., & **Li, X.** (2018). Relationship between vegetation and environment in an arid-hot valley in southwestern China. Sustainability, 10(12), 4774.

## 2017:

3.  Yang W., **Li X.**, Pei J., Sun T., Shao D., Bai J., & Li Y. (2017). Bioavailability of trace metals in sediments of a recovering freshwater coastal wetland in China’s Yellow River Delta, and risk assessment for the macrobenthic community. Chemosphere, 189, 661-671.

<!-- -->

2.  Yang W., **Li X.**, Sun T., Pei J., & Li M. (2017). Macrobenthos functional groups as indicators of ecological restoration in the northern part of China’s Yellow River Delta wetlands. Ecological Indicators, 82, 381-391.

<!-- -->

1.  Yang W., **Li X.**, Sun T., Yang Z., & Li M. (2017). Habitat heterogeneity affects the efficacy of ecological restoration by freshwater releases in a recovering freshwater coastal wetland in China’s Yellow River Delta. Ecological Engineering, 104, 1-12.

## BIORXIV

-   Forgoston, E., Day, S., de Ruiter, P. C., Doelman, A., Hartemink, N., Hastings, A., Hemerik, L., Hening, A., Hofbauer, J., Kefi, S., Kessler, D. A., Klauschies, T., Kuehn, C., **Li, X.**, Moore, J. C., Morrien, E., Neutel, A. M., Pantel, J., Schreiber, S. J., Shaw, L. B., Shnerb, N., Siero, E., Storch, L. S., Thorne, M. A. S., van de Leemput, I., van Velzen, E., Weinans, E. (2023). Stability and Fluctuations in Complex Ecological Systems. arXiv preprint, arXiv:2306.07447.
